server:
  port: 8081
spring:
  application:
    name: seckill-platform-canal
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



