server:
  port: 8005

spring:
  cache:
    type:  simple #指定所使用的缓存管理器
    cache-names: system-drools
  profiles:
    active: ${profile.name}
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
  redis:
    redisson:
      file: classpath:redis/redisson-single.yaml
task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50

feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic