server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: seckill-platform-auth-route
          uri: lb://seckill-platform-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: seckill-platform-system-route
          uri: lb://seckill-platform-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        - id: seckill-platform-sso-route
          uri: lb://seckill-platform-sso
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1
        - id: seckill-platform-service-route
          uri: lb://seckill-platform-service
          predicates:
            - Path=/server/**
          filters:
            - StripPrefix=1
        - id: seckill-platform-search-route
          uri: lb://seckill-platform-search
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/seckill-platform-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    redisson:
      file: classpath:redis/redisson-single.yaml
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/seckill-platform-auth/oauth/token"
      - "/seckill-platform-auth/rsa/publicKey"
      - "/seckill-platform-search/**"
      - "/sso/login"
      - "/sso/register"
      - "/sso/getAuthCode"
      - "/seckill-platform-portal/home/**"
      - "/seckill-platform-portal/product/**"
      - "/system/auth/login"
      - "/system/auth/code"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
##自定义服务的负载均衡策略
seckill-platform-search:
  ribbon:
    #使用的负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #配置的微服务的服务器ip端口
    #listOfServers: localhost:1001, localhost:1002
